In [1]:

from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
##We need to define the vocabulary size 
voc_size = 10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
##One Hot Representation for every word
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[9799, 6508, 3756, 6058],
 [9799, 6508, 3756, 821],
 [9799, 5468, 3756, 6441],
 [6174, 6914, 1317, 3827],
 [6174, 6914, 3501, 1317, 3125],
 [6922, 9799, 943, 3756, 3413],
 [6536, 8828, 3495, 1317]]

In [12]:
##word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [15]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9799 6508 3756 6058]
 [   0    0    0    0 9799 6508 3756  821]
 [   0    0    0    0 9799 5468 3756 6441]
 [   0    0    0    0 6174 6914 1317 3827]
 [   0    0    0 6174 6914 3501 1317 3125]
 [   0    0    0 6922 9799  943 3756 3413]
 [   0    0    0    0 6536 8828 3495 1317]]


In [16]:
##Feature representation
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 245ms/step


array([[[-0.00064005, -0.0215135 ,  0.04687599,  0.04381191,
         -0.03111842, -0.02803342,  0.01363428, -0.03327071,
         -0.03684281,  0.03849974],
        [-0.00064005, -0.0215135 ,  0.04687599,  0.04381191,
         -0.03111842, -0.02803342,  0.01363428, -0.03327071,
         -0.03684281,  0.03849974],
        [-0.00064005, -0.0215135 ,  0.04687599,  0.04381191,
         -0.03111842, -0.02803342,  0.01363428, -0.03327071,
         -0.03684281,  0.03849974],
        [-0.00064005, -0.0215135 ,  0.04687599,  0.04381191,
         -0.03111842, -0.02803342,  0.01363428, -0.03327071,
         -0.03684281,  0.03849974],
        [-0.02353374,  0.00481506, -0.01525757, -0.03618237,
          0.02362373, -0.03851817, -0.01855896, -0.02889737,
          0.03020385, -0.01702031],
        [ 0.01625318, -0.01744591,  0.03321097, -0.01935952,
          0.00307627, -0.04293042,  0.00740305,  0.00354177,
          0.03527576, -0.00804808],
        [ 0.01332051, -0.01915145,  0.0030911 ,  0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 9799, 6508, 3756, 6058])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 73ms/step


array([[-0.00064005, -0.0215135 ,  0.04687599,  0.04381191, -0.03111842,
        -0.02803342,  0.01363428, -0.03327071, -0.03684281,  0.03849974],
       [-0.00064005, -0.0215135 ,  0.04687599,  0.04381191, -0.03111842,
        -0.02803342,  0.01363428, -0.03327071, -0.03684281,  0.03849974],
       [-0.00064005, -0.0215135 ,  0.04687599,  0.04381191, -0.03111842,
        -0.02803342,  0.01363428, -0.03327071, -0.03684281,  0.03849974],
       [-0.00064005, -0.0215135 ,  0.04687599,  0.04381191, -0.03111842,
        -0.02803342,  0.01363428, -0.03327071, -0.03684281,  0.03849974],
       [-0.02353374,  0.00481506, -0.01525757, -0.03618237,  0.02362373,
        -0.03851817, -0.01855896, -0.02889737,  0.03020385, -0.01702031],
       [ 0.01625318, -0.01744591,  0.03321097, -0.01935952,  0.00307627,
        -0.04293042,  0.00740305,  0.00354177,  0.03527576, -0.00804808],
       [ 0.01332051, -0.01915145,  0.0030911 ,  0.03060314,  0.02868604,
         0.04183694, -0.02951453,  0.00495201